#!/bin/env ruby
require_relative "impl"

FS_SIZE   = 70000000
NEED_SIZE = 30000000

main do
	|parser|

	delete = parser.root.size + NEED_SIZE - FS_SIZE

	iter = parser.dirs.each()
	best = iter.next().size
	for dir in iter
		newsize = dir.size
		best = newsize if newsize < best && newsize >= delete
	end

	best
end
